name: auto_hls4ml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.4.0=pyhd8ed1ab_0
  - accessible-pygments=0.0.5=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.10.5=py310ha75aee5_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alabaster=0.7.16=pyhd8ed1ab_0
  - alembic=1.13.2=pyhd8ed1ab_0
  - anyio=4.4.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310ha75aee5_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - async_generator=1.10=pyhd8ed1ab_1
  - atk-1.0=2.38.0=h04ea711_2
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cairo=1.16.0=hbbf8b49_1016
  - certifi=2024.8.30=pyhd8ed1ab_0
  - certipy=0.2.0=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - configurable-http-proxy=4.6.0=he2f69ee_0
  - cryptography=43.0.1=py310h6c63255_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.8.5=py310hf71b8c6_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - dm-tree=0.1.7=py310h769672d_0
  - docutils=0.18.1=py310hff52083_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - etils=1.9.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=h5888daf_0
  - flatbuffers=23.3.3=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py310ha75aee5_1
  - gast=0.4.0=pyh9f0ad1d_0
  - gdk-pixbuf=2.42.10=h6b639ba_2
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=hd590300_0
  - google-auth=2.34.0=pyhff2d567_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - googleapis-common-protos=1.65.0=pyhd8ed1ab_0
  - graphite2=1.3.13=h59595ed_1003
  - graphviz=7.1.0=h2e5815a_0
  - greenlet=3.1.0=py310hf71b8c6_2
  - grpcio=1.51.1=py310h4a5735c_1
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h977cf35_4
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py310hf054cd7_102
  - harfbuzz=7.3.0=hdb3a94d_0
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=72.1=hcb278e6_0
  - idna=3.9=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.27.0=pyh707e725_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-book=0.15.1=pyhd8ed1ab_0
  - jupyter-cache=0.6.1=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_0
  - jupyter_contrib_nbextensions=0.7.0=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_highlight_selected_word=0.2.0=pyhd8ed1ab_1006
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.6.1=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
  - jupyterhub=3.1.1=pyh2a2186d_0
  - jupyterhub-base=3.1.1=pyh2a2186d_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - keras=2.11.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=23_linux64_openblas
  - libcblas=3.9.0=23_linux64_openblas
  - libcurl=8.10.0=hbbe4b11_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgd=2.3.3=hfa28ad5_6
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libglib=2.80.3=h315aac3_2
  - libgomp=14.1.0=h77fa898_1
  - libgrpc=1.51.1=h4fad500_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=23_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.44=hadc24fc_0
  - libprotobuf=3.21.12=hfc55251_2
  - librsvg=2.56.3=h98fae49_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.5.1=h8b53f26_1
  - libtool=2.4.7=he02047a_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libwebp=1.3.1=hbf2b3c1_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.5=h0d562d8_0
  - libxslt=1.1.37=h0054252_1
  - libzlib=1.3.1=h4ab18f5_1
  - linkify-it-py=2.0.3=pyhd8ed1ab_0
  - lxml=4.9.3=py310h9b7343a_1
  - mako=1.3.5=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310ha75aee5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdit-py-plugins=0.4.2=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - multidict=6.1.0=py310ha75aee5_0
  - myst-nb=0.17.2=pyhd8ed1ab_0
  - myst-parser=0.18.1=pyhd8ed1ab_0
  - nbclassic=1.1.0=pyhd8ed1ab_0
  - nbclient=0.7.4=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_1
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbconvert-pandoc=7.16.4=hd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nodejs=18.17.1=hf52ce11_0
  - notebook=6.5.7=pyha770c72_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=3.3.2=hb9d3cd8_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pamela=1.2.0=pyhff2d567_0
  - pandoc=3.4=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=heaa33ce_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.3=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - promise=2.3=py310hff52083_9
  - prompt-toolkit=3.0.47=pyha770c72_0
  - protobuf=4.21.12=py310heca2aa9_0
  - psutil=6.0.0=py310ha75aee5_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyasn1=0.6.1=pyhd8ed1ab_0
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pybtex-docutils=1.0.3=py310hff52083_2
  - pycparser=2.22=pyhd8ed1ab_0
  - pycurl=7.45.3=py310h6811363_2
  - pydata-sphinx-theme=0.15.4=pyhd8ed1ab_0
  - pydot=1.4.2=py310hff52083_4
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.10=he550d4f_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310ha75aee5_1
  - pyzmq=26.2.0=py310h71f11fc_2
  - re2=2023.02.01=hcb278e6_0
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py310h505e2c1_1
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel.yaml=0.18.6=py310h2372a71_0
  - ruamel.yaml.clib=0.2.8=py310h2372a71_0
  - scikit-learn=1.2.2=py310hf7d194e_2
  - send2trash=1.8.3=pyh0d859eb_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hdb0a2a9_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=5.0.2=pyh6c4a22f_0
  - sphinx-book-theme=1.0.1=pyhd8ed1ab_0
  - sphinx-comments=0.0.3=pyh9f0ad1d_0
  - sphinx-copybutton=0.5.2=pyhd8ed1ab_0
  - sphinx-design=0.3.0=pyhd8ed1ab_0
  - sphinx-external-toc=0.3.1=pyhd8ed1ab_1
  - sphinx-jupyterbook-latex=0.5.2=pyhd8ed1ab_0
  - sphinx-multitoc-numbering=0.1.3=pyhd8ed1ab_0
  - sphinx-thebe=0.2.1=pyhd8ed1ab_0
  - sphinx-togglebutton=0.3.2=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-bibtex=2.5.0=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_0
  - sqlalchemy=2.0.34=py310ha75aee5_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310h600f1e7_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.11.1=cpu_py310hd1aba9c_0
  - tensorflow-base=2.11.1=cpu_py310h335d60c_0
  - tensorflow-datasets=4.8.3=pyhd8ed1ab_0
  - tensorflow-estimator=2.11.1=cpu_py310hfed9998_0
  - tensorflow-metadata=1.13.1=pyhd8ed1ab_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.4.1=py310ha75aee5_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240906=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.0.4=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py310ha75aee5_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310ha75aee5_1
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.23.0=py310ha39cb0e_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - calmjs-parse==1.3.1
      - conifer==0.2b0
      - contourpy==1.2.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - filelock==3.16.0
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - hls4ml==0.0.0
      - huggingface-hub==0.25.1
      - ipywidgets==8.1.5
      - julia==0.6.2
      - jupyterlab-widgets==3.0.13
      - keras-tuner==1.4.7
      - kiwisolver==1.4.7
      - kt-legacy==1.0.5
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - networkx==3.3
      - notedown==1.5.1
      - numpy==1.22.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.16.2
      - pandas==2.2.2
      - pandoc-attributes==0.1.7
      - parse==1.6.5
      - pillow==10.4.0
      - ply==3.11
      - ptflops==0.7.4
      - pybind11==2.13.6
      - pycocotools==2.0.8
      - pydigitalwavetools==1.1
      - pyparser==1.0
      - pysr==0.16.3
      - qkeras==0.9.0
      - regex==2024.9.11
      - safetensors==0.4.5
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.15.0
      - setproctitle==1.3.3
      - setuptools==74.1.2
      - smmap==5.0.1
      - sympy==1.13.2
      - tensorflow-model-optimization==0.7.3
      - thop==0.1.1-2209072238
      - timm==1.0.9
      - tokenizers==0.20.1
      - torch==2.4.1
      - torch-summary==1.4.5
      - torchprofile==0.0.4
      - torchvision==0.19.1
      - transformers==4.45.2
      - triton==3.0.0
      - tzdata==2024.1
      - wandb==0.18.3
      - widgetsnbextension==4.0.13
      - yacs==0.1.8
prefix: /home/chengwei/anaconda3/envs/auto_hls4ml
